spring:
    application:
        name: BatchDefinitiveGuideMaven
    datasource:  # Database Connect
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 33125789
        initialization-mode: always
        #continue-on-error: true
    batch:
        initialize-schema: always
            # 스프링 배치 메타데이터 테이블을 자동 생성 여부
            # always: 애플리케이션 실행시 마다 스크립트를 실행. DROP문이 없으며 오류가 발생하면 무시.
            # never: 스크립트를 실행하지 않음.
            # embedded(default): 내장 데이터베이스를 사용. 애플리케이션 실행 시마다 데이터가 초기화됨.
        job:
            names: ${job.name:NONE}  # NONE 지정한 Batch Job만 실행
            enabled: false
